"""fix table name errors

Revision ID: 081b3ac0d231
Revises: cd71e13771b4
Create Date: 2021-05-31 12:00:21.637536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b3ac0d231'
down_revision = 'cd71e13771b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_fullname', sa.String(), nullable=True))
    op.drop_column('order', 'custumer_fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('custumer_fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'customer_fullname')
    # ### end Alembic commands ###
