[development]
APP_VERSION="1"
MAIN_APP = "order"
API_V1_STR = "/order"
APP_NAME = "Order"
BASE_URL_PRODUCT = "http://localhost:8081"
BASE_URL_USER = "http://localhost:8082"
BROKER_USER = "brokeruser"
BROKER_PASS = "brokerpass"
BROKER_PORT = "5672"
BROKER_SERVER = "rabbitmq"
BROKER_VHOST =  "/"
BROKER_QUEUE_CREATE_ORDER = "created_order"
BROKER_EXCHANGE_ORDERS = "orders"
BROKER_STOP_DELAY=60
BROKER_MAX_DELAY=30
MICROSERVICES_TIMEOUT=5
MICROSERVICE_MAX_SECONDS_RETRY=8
MICROSERVICE_MAX_SECONDS_WAIT=4
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
DIAGNOSE=true

[testing]
MAIN_APP = "order"
API_V1_STR = "/order"
APP_NAME = "Order"
BASE_URL_PRODUCT = "http://product-service:8080"
BASE_URL_USER = "http://user-service:8080"
BROKER_USER = "hellofresh"
BROKER_PASS = "food"
BROKER_PORT = "5672"
BROKER_SERVER = "rabbitmq"
BROKER_VHOST =  "/"
BROKER_QUEUE_CREATE_ORDER = "created_order"
BROKER_EXCHANGE_ORDERS = "orders_test"
BROKER_STOP_DELAY=60
BROKER_MAX_DELAY=30
MICROSERVICES_TIMEOUT=1
MICROSERVICE_MAX_SECONDS_RETRY=10
MICROSERVICE_MAX_SECONDS_WAIT=2
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
DIAGNOSE=true
